################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
solar/v1.2/IQ/source/CNTL_2P2Z_IQ.obj: ../solar/v1.2/IQ/source/CNTL_2P2Z_IQ.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="solar/v1.2/IQ/source/CNTL_2P2Z_IQ.d" --obj_directory="solar/v1.2/IQ/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

solar/v1.2/IQ/source/CNTL_2P2Z_IQ_ASM.obj: ../solar/v1.2/IQ/source/CNTL_2P2Z_IQ_ASM.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="solar/v1.2/IQ/source/CNTL_2P2Z_IQ_ASM.d" --obj_directory="solar/v1.2/IQ/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

solar/v1.2/IQ/source/CNTL_3P3Z_IQ.obj: ../solar/v1.2/IQ/source/CNTL_3P3Z_IQ.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="solar/v1.2/IQ/source/CNTL_3P3Z_IQ.d" --obj_directory="solar/v1.2/IQ/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

solar/v1.2/IQ/source/CNTL_3P3Z_IQ_ASM.obj: ../solar/v1.2/IQ/source/CNTL_3P3Z_IQ_ASM.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="solar/v1.2/IQ/source/CNTL_3P3Z_IQ_ASM.d" --obj_directory="solar/v1.2/IQ/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

solar/v1.2/IQ/source/CNTL_PI_IQ.obj: ../solar/v1.2/IQ/source/CNTL_PI_IQ.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="solar/v1.2/IQ/source/CNTL_PI_IQ.d" --obj_directory="solar/v1.2/IQ/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

solar/v1.2/IQ/source/RAMPGEN_IQ.obj: ../solar/v1.2/IQ/source/RAMPGEN_IQ.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="solar/v1.2/IQ/source/RAMPGEN_IQ.d" --obj_directory="solar/v1.2/IQ/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

solar/v1.2/IQ/source/SINEANALYZER_DIFF_IQ.obj: ../solar/v1.2/IQ/source/SINEANALYZER_DIFF_IQ.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="solar/v1.2/IQ/source/SINEANALYZER_DIFF_IQ.d" --obj_directory="solar/v1.2/IQ/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

solar/v1.2/IQ/source/SINEANALYZER_DIFF_wPWR_IQ.obj: ../solar/v1.2/IQ/source/SINEANALYZER_DIFF_wPWR_IQ.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="solar/v1.2/IQ/source/SINEANALYZER_DIFF_wPWR_IQ.d" --obj_directory="solar/v1.2/IQ/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


