################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
SGEN/source/C28x_SGEN_LIB/SINTB360.obj: ../SGEN/source/C28x_SGEN_LIB/SINTB360.ASM $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/SINTB360.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/profilec.obj: ../SGEN/source/C28x_SGEN_LIB/profilec.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/profilec.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/rampgc.obj: ../SGEN/source/C28x_SGEN_LIB/rampgc.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/rampgc.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sghp1c.obj: ../SGEN/source/C28x_SGEN_LIB/sghp1c.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sghp1c.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sghp2c.obj: ../SGEN/source/C28x_SGEN_LIB/sghp2c.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sghp2c.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sgt1c.obj: ../SGEN/source/C28x_SGEN_LIB/sgt1c.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sgt1c.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sgt2c.obj: ../SGEN/source/C28x_SGEN_LIB/sgt2c.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sgt2c.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sgt3c.obj: ../SGEN/source/C28x_SGEN_LIB/sgt3c.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sgt3c.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sgt3dc.obj: ../SGEN/source/C28x_SGEN_LIB/sgt3dc.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sgt3dc.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sgti1c.obj: ../SGEN/source/C28x_SGEN_LIB/sgti1c.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sgti1c.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sgti2c.obj: ../SGEN/source/C28x_SGEN_LIB/sgti2c.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sgti2c.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sgti3c.obj: ../SGEN/source/C28x_SGEN_LIB/sgti3c.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sgti3c.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/sgti3dc.obj: ../SGEN/source/C28x_SGEN_LIB/sgti3dc.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/sgti3dc.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SGEN/source/C28x_SGEN_LIB/tzdlgc.obj: ../SGEN/source/C28x_SGEN_LIB/tzdlgc.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="SGEN/source/C28x_SGEN_LIB/tzdlgc.d" --obj_directory="SGEN/source/C28x_SGEN_LIB" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


