################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
UserSource/F2803XAdcProcess.obj: ../UserSource/F2803XAdcProcess.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/F2803XAdcProcess.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/F2803XDevInit.obj: ../UserSource/F2803XDevInit.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/F2803XDevInit.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/F2803XEpwmProcess.obj: ../UserSource/F2803XEpwmProcess.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/F2803XEpwmProcess.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/F2803XGpioProcess.obj: ../UserSource/F2803XGpioProcess.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/F2803XGpioProcess.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/F2803XI2CProcess.obj: ../UserSource/F2803XI2CProcess.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/F2803XI2CProcess.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/F2803XSpiProcess.obj: ../UserSource/F2803XSpiProcess.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/F2803XSpiProcess.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/F2803XT0Process.obj: ../UserSource/F2803XT0Process.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/F2803XT0Process.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/FaultsManage.obj: ../UserSource/FaultsManage.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/FaultsManage.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/GlobalVariable.obj: ../UserSource/GlobalVariable.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/GlobalVariable.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/SoftstartGen.obj: ../UserSource/SoftstartGen.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/SoftstartGen.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/SystemManage.obj: ../UserSource/SystemManage.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/SystemManage.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/pid_reg3.obj: ../UserSource/pid_reg3.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/pid_reg3.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

UserSource/voltagesourceinvlcfltr.obj: ../UserSource/voltagesourceinvlcfltr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="UserSource/voltagesourceinvlcfltr.d" --obj_directory="UserSource" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


