################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
common/source/DSP2803x_Adc.obj: ../common/source/DSP2803x_Adc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_Adc.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_CSMPasswords.obj: ../common/source/DSP2803x_CSMPasswords.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_CSMPasswords.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_CodeStartBranch.obj: ../common/source/DSP2803x_CodeStartBranch.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_CodeStartBranch.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_Comp.obj: ../common/source/DSP2803x_Comp.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_Comp.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_CpuTimers.obj: ../common/source/DSP2803x_CpuTimers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_CpuTimers.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_DBGIER.obj: ../common/source/DSP2803x_DBGIER.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_DBGIER.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_DefaultIsr.obj: ../common/source/DSP2803x_DefaultIsr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_DefaultIsr.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_DisInt.obj: ../common/source/DSP2803x_DisInt.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_DisInt.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_ECan.obj: ../common/source/DSP2803x_ECan.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_ECan.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_ECap.obj: ../common/source/DSP2803x_ECap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_ECap.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_EPwm.obj: ../common/source/DSP2803x_EPwm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_EPwm.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_EQep.obj: ../common/source/DSP2803x_EQep.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_EQep.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_Gpio.obj: ../common/source/DSP2803x_Gpio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_Gpio.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_HRCap.obj: ../common/source/DSP2803x_HRCap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_HRCap.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_I2C.obj: ../common/source/DSP2803x_I2C.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_I2C.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_Lin.obj: ../common/source/DSP2803x_Lin.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_Lin.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_OscComp.obj: ../common/source/DSP2803x_OscComp.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_OscComp.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_PieCtrl.obj: ../common/source/DSP2803x_PieCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_PieCtrl.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_PieVect.obj: ../common/source/DSP2803x_PieVect.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_PieVect.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_Sci.obj: ../common/source/DSP2803x_Sci.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_Sci.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_Spi.obj: ../common/source/DSP2803x_Spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_Spi.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_SysCtrl.obj: ../common/source/DSP2803x_SysCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_SysCtrl.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_TempSensorConv.obj: ../common/source/DSP2803x_TempSensorConv.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_TempSensorConv.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

common/source/DSP2803x_usDelay.obj: ../common/source/DSP2803x_usDelay.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/17.6.0/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=softlib -O1 --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="C:/ti/17.6.0/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/common/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/solar/v1.2/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/headers/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/IQmath/c28/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SGEN/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/SFRA/IQ/include" --include_path="R:/08 - R&D/12 - Marty Ma/Firmware/InverterFWA0/UserInclude" --advice:performance=all --define="_DEBUG" --define="LARGE_MODEL" --define="FLASH" -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="common/source/DSP2803x_usDelay.d" --obj_directory="common/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


